spring.application.name=novatech-backend
server.port=8080

# Kích hoạt profile 'dev' (H2 in-memory) mặc định.
# Để chạy với PostgreSQL, hãy chạy ứng dụng với cờ: --spring.profiles.active=postgres
spring.profiles.active=dev

# Cấu hình log web
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=INFO
